manifest = "8bf9ae2286164020a68ba34d9e9b67b4449b075fd3271d80e0afe45149bbdbe1"

[[dependency]]
package = "github.com/buckaroo-pm/host-core-foundation"
target = "//:core-foundation"

[[dependency]]
package = "github.com/buckaroo-pm/host-security"
target = "//:security"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
target = "//:zlib"

[[dependency]]
package = "github.com/buckaroo-pm/openssl"
target = "//:openssl"

[lock."github.com/buckaroo-pm/host-core-foundation"]
versions = [ "branch=master" ]
revision = "fd7081ffe1244afb86c41c2d41d3603f851feae8"

[lock."github.com/buckaroo-pm/host-security"]
versions = [ "branch=master" ]
revision = "f7aba7ed43bd385648cb550128ce69800172343c"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "1.2.11" ]
revision = "94a70f3274f15bf98b472178e91fd57a6e6c53d8"

[lock."github.com/buckaroo-pm/openssl"]
versions = [ "tag=1.0.2p" ]
revision = "1f1935327083eabb14370b43049f37839975c36f"
