manifest = "fe247766579c308370cd78e9a1d06c631d3e7ac706505b78b4320673418cd839"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
target = "//:zlib"

[[dependency]]
package = "github.com/buckaroo-pm/openssl"
target = "//:openssl"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "1.2.11" ]
revision = "94a70f3274f15bf98b472178e91fd57a6e6c53d8"

[lock."github.com/buckaroo-pm/openssl"]
versions = [ "tag=1.0.2p" ]
revision = "1f1935327083eabb14370b43049f37839975c36f"
